name: sethlowephoto
favicon: null
layout_spectrum: 0.43257
typography_spectrum: 0.16941
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#465266'
    - '#bcb4aa'
    - '#72808f'
    - '#321d00'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: 79db5d98-0091-44c5-b288-a8f94a7df2f1
    url: test site
